import Image from "next/image";
import { BsSearch } from "react-icons/bs";
import Head from "next/head";
import axios from "axios";
import { useState } from "react";
import Weather from "../components/Weather";

export default function Home() {
	const [city, setCity] = useState("");
	const [weather, setWeather] = useState({});
	const [loading, setLoading] = useState(false);

	const fetchWeather = async (e) => {
		e.preventDefault();
		setLoading(true);
		try {
			const geocodingUrl = `https://api.openweathermap.org/geo/1.0/direct?q=${city}&limit=1&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
			const geocodingResponse = await axios.get(geocodingUrl);
			const { lat, lon, country, state } = geocodingResponse.data[0];
			const weatherUrl = `https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
			const weatherResponse = await axios.get(weatherUrl);
			setWeather({
				...weatherResponse.data,
				country,
				state,
			});
		} catch (error) {
			console.error(error);
		}
		setLoading(false);
		setCity("");
	};

	return (
		<div>
			<Head>
				<title>Weather - Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Search */}
			<div className="relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10">
				<form
					onSubmit={fetchWeather}
					className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl"
				>
					<div>
						<input
							onChange={(e) => setCity(e.target.value)}
							className="bg-transparent border-none text-white focus:outline-none text-2xl"
							type="text"
							placeholder="Search city"
						/>
					</div>
					<button onClick={fetchWeather}>
						<BsSearch size={20} />
					</button>
				</form>
			</div>

			{/* Overlay */}
			<div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]" />

			{/* Background image */}
			<Image
				src="https://images.unsplash.com/photo-1580193769210-b8d1c049a7d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1474&q=80"
				alt="background img"
				layout="fill"
				className="object-cover"
			/>

			{/* Weather */}
			{Object.keys(weather).length !== 0 && <Weather data={weather} />}
		</div>
	);
}
